data:
  - cell1-RNA-analysis-Pool-U87-RNA-792-m64220e_210621_231818.hifi_reads.fastq.gz
  - cell2-RNA-analysis-Pool-U937-A2-RNA-793-m64220e_210622_231749.hifi_reads.fastq.gz
  - cell5-RNA-Demultiplex_U87_gDNA-Pool-U87-U937-RNA-828-m64220e_210708_235020.hifi_reads.fastq.gz
sources:
  - U87
  - U937
barcodes:
  U87:
    U87-1:
      5p: CACATATCAGAGTGCGGCAATGAAGTCGCAGGGTTGGGG
      3p: GTACTCTGCGTTGATACCACTGCTTCGCACTCTGATATGTG
    U87-2:
      5p: ACACACAGACTGTGAGGCAATGAAGTCGCAGGGTTGGGG
      3p: GTACTCTGCGTTGATACCACTGCTTCTCACAGTCTGTGTGT
    U87-3:
      5p: ACACATCTCGTGAGAGGCAATGAAGTCGCAGGGTTGGGG
      3p: GTACTCTGCGTTGATACCACTGCTTCTCTCACGAGATGTGT
  U937:
    U937-1:
      5p: CACGCACACACGCGCGGCAATGAAGTCGCAGGGTTGGGG
      3p: GTACTCTGCGTTGATACCACTGCTTCGCGCGTGTGTGCGTG
    U937-2:
      5p: CACTCGACTCTCGCGTGCAATGAAGTCGCAGGGTTGGGG
      3p: GTACTCTGCGTTGATACCACTGCTTACGCGAGAGTCGAGTG
    U937-3:
      5p: CATATATATCAGCTGTGCAATGAAGTCGCAGGGTTGGGG
      3p: GTACTCTGCGTTGATACCACTGCTTACAGCTGATATATATG